# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  flake.nixosModules.performusHw = {
    config,
    lib,
    pkgs,
    modulesPath,
    ...
  }: {
    imports = [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

    boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "uas" "sd_mod"];
    boot.initrd.kernelModules = [];
    boot.kernelModules = ["kvm-intel"];
    boot.extraModulePackages = [];

    fileSystems."/" = {
      device = "/dev/disk/by-uuid/eb9881d7-b31a-4322-b7eb-9fb7d78ca2f0";
      fsType = "ext4";
    };

    fileSystems."/boot" = {
      device = "/dev/disk/by-uuid/3E4F-3E74";
      fsType = "vfat";
      options = ["fmask=0077" "dmask=0077"];
    };

    # Vault RAID 10 Array
    boot.swraid.enable = true;
    boot.swraid.mdadmConf = "MAILADDR root@localhost";
    fileSystems."/mnt/vault" = {
      device = "/dev/disk/by-uuid/859f8fb1-ab95-4c0a-8019-313cf7544aea";
      fsType = "ext4";
      options = ["defaults" "nofail"];
    };

    # Secondary NVME
    fileSystems."/mnt/secondary" = {
      device = "/dev/disk/by-uuid/eaeabb15-d6a2-4897-9785-762ce268dbfe";
      fsType = "ext4";
      options = ["defaults" "nofail"];
    };

    swapDevices = [
      {device = "/dev/disk/by-uuid/05a391c0-d721-405e-8b65-7e07e155d2ec";}
    ];

    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
    hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  };
}
