#!/usr/bin/env bash

set -e

alejandra . &> /dev/null
git diff -U0 *.nix
git add .

HOST=$(hostname)
echo "NixOS Rebuilding host:$HOST..."

set +e
set -o pipefail
sudo nixos-rebuild switch --flake .#$HOST 2>&1 | tee nixos-switch.log
REBUILD_RTN="$?"
set -e
echo "$REBUILD_RTN"
if [ ! $REBUILD_RTN -eq 0 ]; then
    echo
    echo
    echo
    echo "Error summmary:"
    cat nixos-switch.log | grep --color error && false
    exit 1
fi

gen=$(nixos-rebuild list-generations | grep True | awk '{print $1}')
commitMsg="Generation: $gen"
echo $commitMsg
git commit -am $commitMsg
